services:
  - type: web
    name: qr-scanner
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: DB_PATH
        value: /tmp/qr_scans.db
